apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinamna-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kinamna-frontend
  template:
    metadata:
      labels:
        app: kinamna-frontend
    spec:
      containers:
        - name: kinamna-frontend
          image: siddjuugi/kinamna-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kinamna-frontend
spec:
  ports:
    - port: 3010
      targetPort: 3000
  selector:
    app: kinamna-frontend
