apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinamna-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kinamna-frontend
  template:
    metadata:
      labels:
        app: kinamna-frontend
    spec:
      containers:
      - name: kinamna-frontend
        image: dipenbhat557/kinamna-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kinamna-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: kinamna-frontend